spring:
  # Configuração do PostgreSQL (Desenvolvimento)
  datasource:
    url: jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres
    # url: jdbc:postgresql://localhost:5432/salesplatform_db
    username: postgres.colhkldenffkeceivync
    #username: postgres
    # password: postgres
    password: VjSK1IsGaCZ4v2
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  
  # JPA - Desenvolvimento
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  
  # Flyway - Desenvolvimento
  flyway:
    clean-disabled: false

# Logging - Desenvolvimento
logging:
  level:
    root: INFO
    br.com.fsj.salesplatform: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator - Desenvolvimento (mais endpoints expostos)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Server
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

